version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./my-apache-config.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db
    command: ["apache2-foreground", "-D", "FOREGROUND", "-D", "ALLOW_OVERRIDE=All"]
    deploy:
      resources:
        limits:
          memory: 512M
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lgp-manager
      MYSQL_USER: lgp-manager
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
